### ISSUE TITLE
Text structure and examples

### ISSUE THREAD

**Issue by briatte** [sctyner/ggnet-paper#2]
I'd like to suggest using slightly less examples along a different text structure.
### Section 1. Implementations

Once we are done with introducing the topic, we need to present and compare the three implementations. The **Mad Men** example works well to show their similarities, and it can illustrate both undirected and directed graphs.

The **Email** example works well to show a difference between `ggnet2` and the two other implementations. The difference has to do with edge overplotting: `ggnet2` shows all edges in the email network, which creates differences in edge thickness (Figure 3a), while the two others plot only one edge between connected nodes. As a result, edge thickness is not the same in Figure 3a and in the other subfigures of Figure 3. We probably need to fix the text here to discuss weighted networks (more on that later).

Perhaps the **Blood** example can be of some use in that section, if we want to illustrate the use of different network layouts, or if we want to show the raw network data, since the dataset is small.
### Section 2. Temporal networks

Another topic in the text is the representation of temporal networks, which the **Email** example illustrates quite well. This could easily be a section on its own.

There are basically two approaches: use true `ggplot2` facets, or generate multiple plots and assemble them into a single one. `geom_net` shows the first approach, and `ggnet2` the second one; `ggnetwork` currently uses the second approach but I should be able to use the first one, really.

On the topic of temporal networks, see [this new package](https://cran.r-project.org/web/packages/tsna/vignettes/tsna_vignette.html).
### Section 3. Geographic networks

Spatial networks could also be a section on their own. The **Bikes** example seems ideal to me (not too large, might work with `ggmap` once the package gets fixed).

On spatial networks, see also [this package](http://emmanuel.rousseaux.me/r-package-spnet).

---

The text includes many more examples, but their illustrative value-added is not always obvious to me.
- The **Football** example might be useful to show how to color (or style) edges based on an edge attribute. On that topic, I'm pretty sure that the plots in Figure 8 would look better if edge color (instead of linetype) were used to show same-conference ties.
- The **_Misérables**_ network is famous, and it currently illustrates differences in edge size, but edge size is also illustrated by the Bikes example, and the Email example should probably be used to discuss weighted edges.
- The **Yeast** example illustrates the random network layout, but this example seems redundant with the **Blood** example to me.

---

What do you think? We could also have one big section on implementation (which I believe should also cover directed and weighted networks), and another big one on spatial and temporal networks.
### Bipartite networks?

Right now, we do not discuss bipartite networks (or k-partite networks) at all. Perhaps we could ask Pedro Jordano for permission to use [the data from this example](https://pedroj.github.io/bipartite_plots/).

**Comment by heike** [comment]
Francois,

thank you for your comments.
I agree with a lot of things you said, but not all :)
The main thing, I think is, that I wouldn't want to have sections for each
one of these types of networks - like you said, there are many different
types, and the list you gave is definitely not exhaustive.
Similarly, neither one of our approaches solves everything - all of the
implementations are very much static networks, so even with the facetting I
would have never considered the email example to be a true temporal
network. There is much more to a temporal network than just discrete
facetting, and reviewers will see that, any claims beyond that will open us
up to massive criticisms. Keeping the scope of the paper small will allow
us to get the paper out in a reasonable time.

What we have are three different implementations of static networks, that
can be used in some situations, as we show in the examples. What we need to
emphasize, are the commonalities/differences between the implementations.
Otherwise it doesn't make a lot of sense to have three implementations.

I agree that we can emphasize in the examples that there is a temporal
component, or a geographic component, but I wouldn't want to go beyond
that. There are certainly citations missing, it'd be great, if you could
add the links to the packages (and the papers they are based on) in the
appropriate places. Thank you for pointing those out!

With respect to the exact examples - I agree that we can change things
around. This is definitely not a fixed list.
I'd be happy to include an example on a bi- or k-partite network - or
replace one of the existing ones - but you might want to keep that example
back for a later paper of yours discussing visualizations for different
types of networks?

On to specific comments:

> The _Email_ example works well to show a difference between ggnet2 and
> the two other implementations. The difference has to do with edge
> overplotting: ggnet2 shows all edges in the email network, which creates
> differences in edge thickness (Figure 3a), while the two others plot only
> one edge between connected nodes. As a result, edge thickness is not the
> same in Figure 3a and in the other subfigures of Figure 3. We probably need
> to fix the text here to discuss weighted networks (more on that later).
> 
> I'm assuming that you got Sam's email about the paper-ggnet repo, so you
> should have access to the current version.
> The setup is following the R journal style - there is a Rjwrapper.Rnw,
> which needs to be compiled to PDF in RStudio, and it calls our contribution
> tyner-briatte-hofmann.Rnw as a child.

So changes to the paper itself would need to be done in
 tyner-briatte-hofmann.Rnw.

It'd be great, if you could use the command \fb{...} to highlight changes
that you make to the text - that way we can incrementally work through the
text without having to check in github each time for changes.

The difference that you point out for the edges in the blood example are
exactly the ones that I'm looking for - it's good to know what one
implementation is doing differently (better?) than the others.

facetting:

> There are basically two approaches: use true ggplot2 facets, or generate
> multiple plots and assemble them into a single one. geom_net shows the
> first approach, and ggnet2 the second one; ggnetwork currently uses the
> second approach but I should be able to use the first one, really.
> 
> I'd be happy to extend the facetting discussion.
> 
> ---
> 
> The text includes many more examples, but their illustrative value-added
> is not always obvious to me.
> - The _Football_ example might be useful to show how to color (or
>   style) edges based on an edge attribute. On that topic, I'm pretty sure
>   that the plots in Figure 8 would look better if edge color (instead of
>   linetype) were used to show same-conference ties.
> 
> that's again, a difference - keep the edge color in your example. At the
> moment geom_net can't handle that very well, because the edge color is a
> combination of two variables: conference and same/different conference. We
> are thinking of how to include the second piece of information, but for the
> moment, this is a difference.
> - The _Misérables_ network is famous, and it currently illustrates
>   differences in edge size, but edge size is also illustrated by the Bikes
>   example, and the Email example should probably be used to discuss weighted
>   edges.
> 
> OK, point taken - I still like the example though - and in its defense, it
> is not at all easy to find a good way to deal with all the names, which
> shouldn't be such a problem. This is a pretty typical problem for network
> labelling - and we have different approaches to it, which I like.
> - The _Yeast_ example illustrates the random network layout, but this
>   example seems redundant with the _Blood_ example to me.
> 
> The yeast example is trying to show the scope of the layouts in terms of
> number of nodes ... way back layouts were terribly slow, so one would have
> never stuffed 4000 nodes into a layout and expected a result the same day.
> I agree that the result is not hugely interpretable, but at that size
> interpretation becomes a question of screen/paper space.
> 
> All the best,

Heike

**Comment by briatte** [comment]
Thanks for the feedback, @heike.

I agree with your opening remarks: we definitely do not cover every aspect of network visualization, and the most important element to stress is what differs from one implementation to the other.

> I agree that we can emphasize in the examples that there is a temporal
> component, or a geographic component, but I wouldn't want to go beyond
> that. There are certainly citations missing, it'd be great, if you could
> add the links to the packages (and the papers they are based on) in the
> appropriate places. Thank you for pointing those out!

Will do. And we are on the same page here: I know that what we have are (very) minimal implementations of spatial/temporal features.

> I'd be happy to include an example on a bi- or k-partite network - or replace one of the existing ones - but you might want to keep that example back for a later paper of yours discussing visualizations for different types of networks?

I'm fine with the idea to leave things as they are, and not mention bipartite networks in the paper. If you want to have them, though, it should not be that difficult to add.

Thanks also for the specific comments. My point was just to get the conversation started on what each example brings to the paper—I now understand the Yeast example better, for instance.
